# parameters for the baseline mpc agent

agent_kwargs:
    num_episodes: 10
    velocity_target: 14 # m/s
    step_size: 8 # number of indicies b/w waypoints
    save_transitions: False
    save_path: False
    plot: False

