agent_kwargs:
    experiment_name: 'SAC'
    make_random_actions: 0
    inference_only: False
    load_checkpoint: False
    record_experience: False
    encoder_switch: 1
    use_encoder_type: "vae_small" # ['vae', 'vae_small', 'resent']
    resnet:
        backbone: "resnet18"
        pretrained: True
        speed_hiddens:  [32, 32]
        hiddens: [512, 512, 512, 256, 32]
        actor_hiddens: [512, 128, 32]
        latent_dims: 513
    vae:
        vae_chkpt_statedict: '${PREFIX}/l2r/checkpoints/encoder/thruxton/vae/vae-144hw-32l-thruxton.statedict'
        vae_chkpt_pth: '${PREFIX}/l2r/checkpoints/encoder/thruxton/vae/vae-144hw-32l-thruxton.pt'
        latent_dims: 32
        im_w: 144
        im_h: 144
    vae_small:
        vae_chkpt_statedict: './common/models/vae_144w_42h_32latent.pth'
        latent_dims: 32
        hiddens: [32, 64, 64, 32, 32]
        speed_hiddens:  [8, 8]
        actor_hiddens: [64, 64, 32]
        im_c: 3
        im_w: 144
        im_h: 42
        ac_input_dims: 32 
    seed: 0
    gamma: 0.99
    polyak: 0.995
    lr: 0.003
    alpha: 0.2
    num_test_episodes: 1
    safety_margin: 4.2
    save_episodes: 1
    save_freq: 1
    total_steps: 250_000
    replay_size: 250_000
    batch_size: 256
    start_steps: 2000
    update_after: 2000
    update_every: 1
    eval_every: 5000
    max_ep_len: 50000
    im_w: 144
    im_h: 144
    checkpoint: '${PREFIX}/l2r/checkpoints/agent/thruxton/sac/sac_episode_1000.pt'
    model_save_path: '${PREFIX}/l2r/results/${DIRHASH}workspaces/${USER}/results'
    track_name: 'Thruxton'
    safety_data: '${PREFIX}/l2r/datasets/l2r/datasets/safety_sets'
    record_dir: '${PREFIX}/l2r/datasets/l2r/datasets/safety_records_dataset/'
