env_kwargs:
    multimodal: True
    eval_mode: True
    n_eval_laps: 1
    max_timesteps: 5000
    obs_delay: 0.1
    not_moving_timeout: 100
    reward_pol: 'custom'
    provide_waypoints: False
    reward_kwargs:
        oob_penalty: 5.0
        min_oob_penalty: 25.0
        max_oob_penalty: 125.0
    controller_kwargs:
        sim_version: 'ArrivalSim-linux-0.7.0.182276'
        quiet: False
        start_container: False
        sim_running: True
        sim_path: '/data/l2r/sims/original/ArrivalSim-linux-0.7.0.182276/LinuxNoEditor'
        user: '${USER}'
    action_if_kwargs:
        max_accel: 6.
        min_accel: -16
        max_steer: .3
        min_steer: -.3
        ip: '0.0.0.0'
        port: 7077
    cameras:
        CameraFrontRGB:
            Addr: 'tcp://127.0.0.1:8008'
            Format: ColorBGR8
            bAutoAdvertise: True
            FOVAngle: 90
            Width: 512
            Height: 384
        CameraLeftRGB:
            Addr: 'tcp://0.0.0.0:8009'
            Format: ColorBGR8
            bAutoAdvertise: True
            FOVAngle: 90
            Width: 512
            Height: 384
        CameraRightRGB:
            Addr: 'tcp://0.0.0.0:8010'
            Format: ColorBGR8
            bAutoAdvertise: True
            FOVAngle: 90
            Width: 512
            Height: 384
        CameraFrontSegm:
            Addr: 'tcp://0.0.0.0:9008'
            FOVAngle: 90
            Width: 512
            Height: 384
        CameraLeftSegm:
            Addr: 'tcp://0.0.0.0:9009'
            FOVAngle: 90
            Width: 512
            Height: 384
        CameraRightSegm:
            Addr: 'tcp://0.0.0.0:9010'
            FOVAngle: 90
            Width: 512
            Height: 384
        CameraBirdsEye:
            Addr: 'tcp://0.0.0.0:10008'
            FOVAngle: 90
            Width: 512
            Height: 384
        CameraBirdsEyeSegm:
            Addr: 'tcp://0.0.0.0:10009'
            FOVAngle: 90
            Width: 512
            Height: 384
    pose_if_kwargs:
        ip: '0.0.0.0'
        port: 7078
    logger_kwargs:
        default: True

sim_kwargs:
    racetrack: 'Thruxton'
    active_sensors: # static sensors configuration is above; this controls whether they are active
        - CameraFrontRGB
    driver_params:
        DriverAPIClass: 'VApiUdp'
        DriverAPI_UDP_SendAddress: '0.0.0.0'
    camera_params:
        Format: ColorBGR8
        FOVAngle: 90
        Width: 512
        Height: 384
        bAutoAdvertise: True
    vehicle_params: False

