agent_kwargs:
    experiment_name: 'EXPERIMENT_NAME'
    make_random_actions: 0
    inference_only: False
    record_experience: False
    load_checkpoint: False
    seed: 0
    save_episodes: 1
    save_freq: 1
    eval_every: 5000
    max_ep_len: 50000
    save_path: '${PREFIX}/l2r/results/${DIRHASH}workspaces/${USER}/results'
    safety_data: '${PREFIX}/l2r/datasets/safety_sets'
    record_dir: '${PREFIX}/l2r/datasets/safety_records_dataset/'

